apiVersion: v1
kind: Service
metadata:
  name: orchestration-service
  labels:
    app: orchestration-service
spec:
  selector:
    app: orchestration-service
  ports:
    - name: http
      port: 8022       # the port the Service exposes inside the cluster
      targetPort: 8022 # containerPort in the Pod
  type: NodePort
  nodePort: 30022
  # or LoadBalancer if you're in a cloud environment
  # port in the range 30000-32767