apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestration-service-deployment
  labels:
    app: orchestration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestration-service
  template:
    metadata:
      labels:
        app: orchestration-service
    spec:
      containers:
      - name: orchestration-service
        image: k8s-poc-orchestration-service:latest
        imagePullPolicy: Never   # To use the local image if available
        ports:
          - containerPort: 8022
        # If you need env vars for anything, specify them here:
        # env:
        #   - name: SOME_ENV
        #     value: "some_value"
